version: '3'

services:
  fuseki:
    container_name: skosmos-fuseki
    image: stain/jena-fuseki
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx2g
    ports:
     - 3030:3030
  # You can uncomment the line below to have a local volume bound onto the container, or
  # visit https://hub.docker.com/r/stain/jena-fuseki/ for other alternatives
  # volumes:
  #  - ${PWD}/fuseki:/fuseki
  web:
    container_name: skosmos-web
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - fuseki

# once the environment has been created:
# 1. create dataset
# >curl -I -u admin:admin -XPOST --data "dbName=skosmos&dbType=tdb" -G http://localhost:3030/$/datasets/
# 2. load example vocabulary
# >curl -I -X POST -H Content-Type:text/turtle -T vocabularies.ttl -G http://localhost:3030/skosmos/data
